import type { BidraListing } from "./types";

export const homeCategories = [
  "Home & furniture",
  "Electronics",
  "Tools",
  "Vehicles",
  "Garden",
  "Sports",
  "Fashion",
  "Kids",
  "Wanted",
];

export const browseCategories = [
  "All",
  "Home & furniture",
  "Electronics",
  "Tools",
  "Vehicles",
  "Garden",
  "Sports",
  "Fashion",
  "Wanted",
];

export const homeListings: BidraListing[] = [
  {
    id: "home-1",
    title: "Timber dining table, six seats",
    price: "$520",
    location: "New Farm, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Dining table listing",
    seller: "Brisbane Home Finds",
    sellerRating: "Verified seller",
    featured: true,
    isSaved: true,
  },
  {
    id: "home-2",
    title: "Road bike, recently serviced",
    price: "$430",
    location: "Paddington, QLD",
    mode: "Timed offer",
    offerSummary: "Current offer $390",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Road bike listing",
    seller: "Cycle Corner",
    sellerRating: "4.9 seller score",
  },
  {
    id: "home-3",
    title: "Cordless drill with battery kit",
    price: "$140",
    location: "Southport, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Cordless drill listing",
    seller: "Tool Shed Co",
    sellerRating: "Pickup ready",
  },
  {
    id: "home-4",
    title: "Two-seater sofa in charcoal",
    price: "$280",
    location: "Chermside, QLD",
    mode: "Offers open",
    offerSummary: "Highest offer $240",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Sofa listing",
    seller: "Northside Living",
    sellerRating: "Fast replies",
  },
  {
    id: "home-5",
    title: "iPad 10th gen, 64GB",
    price: "$460",
    location: "West End, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Tablet listing",
    seller: "Tech Loop",
    sellerRating: "Trusted device checks",
  },
  {
    id: "home-6",
    title: "Outdoor setting, four chairs",
    price: "$210",
    location: "Ipswich, QLD",
    mode: "Timed offer",
    offerSummary: "Current offer $185",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Outdoor setting listing",
    seller: "Patio Market",
    sellerRating: "Weekend pickup",
  },
  {
    id: "home-7",
    title: "Mountain bike, medium frame",
    price: "$390",
    location: "Logan, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Mountain bike listing",
    seller: "Trail Swap",
    sellerRating: "Inspected listing",
  },
  {
    id: "home-8",
    title: "Coffee machine with grinder",
    price: "$260",
    location: "Toowong, QLD",
    mode: "Offers open",
    offerSummary: "Highest offer $230",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Coffee machine listing",
    seller: "Kitchen Finds",
    sellerRating: "3 month usage",
  },
];

export const browseListings: BidraListing[] = [
  ...homeListings,
  {
    id: "browse-9",
    title: "Fridge 350L, clean and cold",
    price: "$320",
    location: "Wynnum, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Fridge listing",
    seller: "Bay Appliances",
    sellerRating: "Delivery available",
  },
  {
    id: "browse-10",
    title: "Camping pack with tent",
    price: "$170",
    location: "Morningside, QLD",
    mode: "Timed offer",
    offerSummary: "Current offer $150",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Camping pack listing",
    seller: "Weekend Gear",
    sellerRating: "Ready today",
  },
  {
    id: "browse-11",
    title: "Desk and ergonomic chair bundle",
    price: "$290",
    location: "Indooroopilly, QLD",
    mode: "Buy Now",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Desk and chair listing",
    seller: "Work From Home Hub",
    sellerRating: "Trusted handover",
  },
  {
    id: "browse-12",
    title: "Portable speaker pair",
    price: "$95",
    location: "Burleigh Heads, QLD",
    mode: "Offers open",
    offerSummary: "Highest offer $82",
    imageSrc: "/brand/hero-clouds.png",
    imageAlt: "Portable speakers listing",
    seller: "Audio Lane",
    sellerRating: "Local pickup",
  },
];
