export const FULL_CATEGORIES = [
  "Vehicles",
  "Vehicle Parts & Accessories",
  "Home & Furniture",
  "Home & Garden",
  "Appliances",
  "Tools & DIY",
  "Tech & Electronics",
  "Phones & Accessories",
  "Computers",
  "Gaming",
  "Fashion & Wearables",
  "Beauty & Personal Care",
  "Sports & Outdoors",
  "Bikes & Scooters",
  "Kids & Toys",
  "Baby & Nursery",
  "Books & Media",
  "Music & Instruments",
  "Collectibles & Vintage",
  "Jewellery & Watches",
  "Art",
  "Office & Business",
  "Industrial",
  "Pet Supplies (NO LIVE ANIMALS)",
  "Health & Medical (non-prescription)",
  "Tickets (where permitted)",
  "Services",
  "Other",
] as const;

export type Category = (typeof FULL_CATEGORIES)[number];
